apiVersion: v1
kind: Service
metadata:
  name: mspayment
  namespace: sit
  labels:
    app: mspayment
spec:
  selector:
    app: mspayment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8995