apiVersion: apps/v1
kind: Deployment
metadata:
  name: mspayment
  namespace: sit
  labels:
    app: mspayment
    version: v1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: mspayment
  template:
    metadata:
      labels:
        app: mspayment
        version: v1
    spec:
      containers:
      - name: mspayment
        image: taufik90/ms-payment:6
        imagePullPolicy: Always
        ports:
        - containerPort: 8995
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck/healty
            port: 8995
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck/healty
            port: 8995
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 60"]
        env:
         - name: ACC_KEY_ID
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: ACC_KEY_ID
         - name: FIREBASE_CLIENT_EMAIL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: FIREBASE_CLIENT_EMAIL
         - name: FIREBASE_DB_URL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: FIREBASE_DB_URL
         - name: FIREBASE_PRIVATE_KEY
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: FIREBASE_PRIVATE_KEY
         - name: FIREBASE_PROJECT_ID
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: FIREBASE_PROJECT_ID
         - name: HOST_MAIL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: HOST_MAIL
         - name: LOGGER_LEVEL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: LOGGER_LEVEL
         - name: MS_ACCOUNT_V1_URL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MS_ACCOUNT_V1_URL
         - name: MS_AUTH_V1_URL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MS_AUTH_V1_URL
         - name: MS_SUPPORT_V1_URL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MS_SUPPORT_V1_URL
         - name: MYSQL_DATABASE
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MYSQL_DATABASE
         - name: MYSQL_HOSTNAME
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MYSQL_HOSTNAME
         - name: MYSQL_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MYSQL_PASSWORD
         - name: MYSQL_PORT
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MYSQL_PORT
         - name: MYSQL_USERNAME
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MYSQL_USERNAME
         - name: OSS_ENDPOINT
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: OSS_ENDPOINT
         - name: OSS_REGION
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: OSS_REGION
         - name: PASS_MAIL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: PASS_MAIL
         - name: PORT
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: PORT
         - name: PORT_MAIL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: PORT_MAIL
         - name: SCR_ACC_KEY
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: SCR_ACC_KEY
         - name: SECRET
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: SECRET
         - name: SERVICE_NAME
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: SERVICE_NAME
         - name: SSL_SEQUELIZE
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: SSL_SEQUELIZE
         - name: USER_MAIL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: USER_MAIL
         - name: MIDTRANS_PASS
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MIDTRANS_PASS
         - name: MIDTRANS_URL
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MIDTRANS_URL
         - name: MIDTRANS_USR
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MIDTRANS_USR
         - name: MQ_HOSTNAME
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MQ_HOSTNAME
         - name: MQ_PASSWORD
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MQ_PASSWORD
         - name: MQ_USERNAME
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MQ_USERNAME
         - name: MQ_VHOST
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: MQ_VHOST
         - name: NAMESPACE
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: NAMESPACE
         - name: ENVIRONMENT
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: ENVIRONMENT
         - name: CLUSTER
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: CLUSTER
         - name: KUBE_CLIENT_SCHEDULE
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: KUBE_CLIENT_SCHEDULE
         - name: SELECTOR
           valueFrom:
            secretKeyRef:
              name: mspayment-secret
              key: SELECTOR
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always